# Numpy Tutorial

In [1]:
import numpy as np

# Creating numpy arrays

In [2]:
my_list = [1.,2.,3., 4.]
mynparray = np.array(my_list)
print(mynparray)

[1. 2. 3. 4.]


Initialize an array of all zeroes, initialize an array of all ones (1-D and 2-D)

In [3]:
one_vector = np.ones(4)
print(one_vector)

[1. 1. 1. 1.]


In [4]:
one2Darray = np.ones((2,4))
print(one2Darray)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
zero_vector = np.zeros(4)
print(zero_vector)

[0. 0. 0. 0.]


#Inititalize an empty array

In [6]:
empty_vector = np.empty(5)
print(empty_vector)

[2.86588430e-316 2.94251111e-316 3.53273024e-316 4.70847564e-316
 2.30751536e+175]


# Accessing array elements

In [9]:
# Accessing elements of the vector mynparray
mynparray[0]

1.0

In [11]:
# Accessing elements of 2D array
my_matrix = np.array([[1,2,3],[4,5,6]])
print(my_matrix)

[[1 2 3]
 [4 5 6]]


In [12]:
print(my_matrix[1,2])

6


In [13]:
print(my_matrix[0:2,2])

[3 6]


In [14]:
print(my_matrix[0,0:2])

[1 2]


We can also pass a list of indices

In [15]:
fib_indices = [1,1,2,3]
random_vector = np.random.random(10)
print(random_vector)

[0.21358038 0.90478361 0.91822586 0.53281053 0.68440763 0.17980619
 0.54337278 0.57704999 0.67382225 0.76328754]


In [16]:
print(random_vector[fib_indices])

[0.90478361 0.90478361 0.91822586 0.53281053]


Use true or false to select values

In [18]:
my_vector = np.array([1,2,3,4])
select_index = np.array([True,False,True,False])
print(my_vector[select_index])

[1 3]


In [20]:
#For 2D arrays we can select specific rows and columns
select_cols = np.array([True,False,True])
select_rows = np.array([False,True])

print(my_matrix[:,select_cols])
print(my_matrix[select_rows,:])

[[1 3]
 [4 6]]
[[4 5 6]]


# Operation on Arrays

In [21]:
my_array = np.array([1.,2.,3.,4.])
print(my_array)

[1. 2. 3. 4.]


In [22]:
print(my_array*my_array)

[ 1.  4.  9. 16.]


In [23]:
print(my_array-np.ones(4))

[0. 1. 2. 3.]


In [25]:
print(np.sum(my_array))

10.0


In [26]:
print(np.mean(my_array))

2.5


In [27]:
print(np.sum(my_array)/len(my_array))

2.5


# Dot Product

In [28]:
array1 = np.array([1.,2.,3.,4.])
array2 = np.array([2.,3.,4.,5.])
print(np.dot(array1,array2))

40.0
